#!/usr/bin/env python3
# test_id: package.documentation.integrity
# api_ids: [package.docs.integrity]
# req_ids: [REQ-08]
# patterns: [DOC-LINK-INTEGRITY]
"""Validate package Markdown files without external documentation tooling.

The check is intentionally small and deterministic. It does not try to become a
complete Markdown renderer; instead it catches the failure modes that make the
package documentation hard to consume in ordinary Markdown viewers: unbalanced
fenced code blocks, malformed local links, and links to missing files or
headings.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path
import re
import sys


LINK_RE = re.compile(r"(?<!!)\[[^\]]+\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
HEADING_RE = re.compile(r"^\s{0,3}(#{1,6})\s+(.+?)\s*#*\s*$")
FENCE_RE = re.compile(r"^\s*(```|~~~)")


def markdown_files(root: Path) -> list[Path]:
    """Return the Markdown files that are part of the distributable test package."""

    docs_root = root / "docs"
    if not docs_root.exists():
        return []
    return sorted(path for path in docs_root.rglob("*.md") if path.is_file())


def slugify_heading(text: str) -> str:
    """Build a Markdown heading slug for local anchor checks."""

    text = text.strip().lower()
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"[^a-z0-9 _-]", "", text)
    text = re.sub(r"\s+", "-", text)
    return text.strip("-")


def heading_anchors(path: Path) -> set[str]:
    """Collect anchor names generated by headings in one Markdown file."""

    anchors: set[str] = set()
    counts: dict[str, int] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = HEADING_RE.match(line)
        if not match:
            continue
        base = slugify_heading(match.group(2))
        count = counts.get(base, 0)
        counts[base] = count + 1
        anchors.add(base if count == 0 else f"{base}-{count}")
    return anchors


def split_link_target(raw: str) -> tuple[str, str]:
    """Split a Markdown link target into path and anchor parts."""

    target = raw.strip()
    if "#" not in target:
        return target, ""
    path_part, anchor = target.split("#", 1)
    return path_part, anchor


def external_or_special_link(target: str) -> bool:
    """Return true for links that this offline package check should not resolve."""

    lowered = target.lower()
    return (
        "://" in lowered
        or lowered.startswith("mailto:")
        or lowered.startswith("tel:")
    )


def validate_markdown_file(path: Path, root: Path) -> tuple[list[str], int]:
    """Validate one Markdown file and return failures plus checked link count."""

    failures: list[str] = []
    text = path.read_text(encoding="utf-8", errors="replace")
    in_fence = False
    link_count = 0

    for line_no, line in enumerate(text.splitlines(), start=1):
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        for match in LINK_RE.finditer(line):
            raw_target = match.group(1)
            if external_or_special_link(raw_target):
                continue
            link_count += 1
            target_path, anchor = split_link_target(raw_target)
            target_file = path if target_path == "" else (path.parent / target_path).resolve()
            try:
                target_file.relative_to(root.resolve())
            except ValueError:
                failures.append(f"{path.relative_to(root)}:{line_no}:link_leaves_package:{raw_target}")
                continue
            if not target_file.exists():
                failures.append(f"{path.relative_to(root)}:{line_no}:missing_link_target:{raw_target}")
                continue
            if anchor and anchor not in heading_anchors(target_file):
                failures.append(f"{path.relative_to(root)}:{line_no}:missing_anchor:{raw_target}")

    if in_fence:
        failures.append(f"{path.relative_to(root)}:unclosed_fenced_code_block")

    first_nonempty = next((line for line in text.splitlines() if line.strip()), "")
    if not first_nonempty.startswith("#"):
        failures.append(f"{path.relative_to(root)}:missing_top_level_heading")

    return failures, link_count


def write_summary(root: Path, status: str, files_checked: int, links_checked: int, failures: list[str]) -> None:
    """Write machine-readable evidence for completeness and validation reports."""

    out = root / "manifests" / "documentation_summary.yaml"
    lines = [
        f"status: {status}",
        f"generated_at_utc: {datetime.now(timezone.utc).isoformat()}",
        f"files_checked: {files_checked}",
        f"links_checked: {links_checked}",
        "failed_checks:",
    ]
    lines += [f"  - {failure}" for failure in failures] or ["  []"]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="Test package root containing docs/")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    failures: list[str] = []
    total_links = 0
    files = markdown_files(root)
    if not files:
        failures.append("missing_markdown_docs")

    for path in files:
        file_failures, link_count = validate_markdown_file(path, root)
        failures.extend(file_failures)
        total_links += link_count

    status = "pass" if not failures else "fail"
    write_summary(root, status, len(files), total_links, failures)
    for failure in failures:
        print(f"FAILED: {failure}")
    return 0 if status == "pass" else 1


if __name__ == "__main__":
    sys.exit(main())
