status: complete
generated_at_utc: 2026-05-06T13:27:28.849348+00:00
failed_checks:
  []
coverage_summary: manifests/coverage_summary.yaml
documentation_summary: manifests/documentation_summary.yaml
mutation_summary: manifests/mutation_summary.yaml
docker_validation: manifests/docker_validation.yaml
misra_advisory_summary: manifests/misra_advisory_summary.yaml
vendor_compiler_summary: manifests/vendor_compiler_summary.yaml
open_assumptions:
  []
