/**
 * @file sstl_function.h
 * @brief C99 SSTL public header with static, allocation-free API surface.
 *
 * The declarations in this file are part of the local SSTL contract. They are
 * documented for Doxygen consumers and for maintainers reading the headers
 * directly. Keep behavior aligned with the SSTL public contract and tests,
 * and avoid introducing hosted STL dependencies into implementation
 * headers.
 */
#ifndef SSTL_C_FUNCTION_H
/** @def SSTL_C_FUNCTION_H
 * @brief Include guard for sstl_function.h.
 */
#define SSTL_C_FUNCTION_H
#include "sstl_config.h"

/** @def SSTL_FUNCTION0_DECLARE
 * @brief Declare the typed C SSTL API family generated by `SSTL_FUNCTION0_DECLARE`.
 */
#define SSTL_FUNCTION0_DECLARE(NAME, R) \
  typedef R (*NAME##_fn)(void* ctx); \
  typedef struct NAME { NAME##_fn fn; /**< @brief Callable target pointer, or null when invalid. */ void* ctx; /**< @brief Caller-owned context pointer passed to the target on every invocation. */ } NAME; \
  /** \
   * @brief Run the generated make operation for this typed SSTL family. \
   * @param fn Callable target or function pointer. \
   * @param ctx Caller-owned callback context. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE NAME NAME##_make(NAME##_fn fn, void* ctx); \
  /** \
   * @brief Run the generated valid operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @return `true` when the documented condition holds; otherwise `false`. \
   */ \
  SSTL_C_INLINE bool NAME##_valid(const NAME* f); \
  /** \
   * @brief Run the generated call operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE R NAME##_call(const NAME* f);

/** @def SSTL_FUNCTION0_DEFINE
 * @brief Define the typed C SSTL API family generated by `SSTL_FUNCTION0_DEFINE`.
 */
#define SSTL_FUNCTION0_DEFINE(NAME, R) \
  /** \
   * @brief Run the generated make operation for this typed SSTL family. \
   * @param fn Callable target or function pointer. \
   * @param ctx Caller-owned callback context. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE NAME NAME##_make(NAME##_fn fn, void* ctx) { NAME f; f.fn = fn; f.ctx = ctx; return f; } \
  /** \
   * @brief Run the generated valid operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @return `true` when the documented condition holds; otherwise `false`. \
   */ \
  SSTL_C_INLINE bool NAME##_valid(const NAME* f) { return f->fn != 0; } \
  /** \
   * @brief Run the generated call operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE R NAME##_call(const NAME* f) { return f->fn(f->ctx); }

/** @def SSTL_FUNCTION1_DECLARE
 * @brief Declare the typed C SSTL API family generated by `SSTL_FUNCTION1_DECLARE`.
 */
#define SSTL_FUNCTION1_DECLARE(NAME, R, A0) \
  typedef R (*NAME##_fn)(void* ctx, A0 a0); \
  typedef struct NAME { NAME##_fn fn; /**< @brief Callable target pointer, or null when invalid. */ void* ctx; /**< @brief Caller-owned context pointer passed to the target on every invocation. */ } NAME; \
  /** \
   * @brief Run the generated make operation for this typed SSTL family. \
   * @param fn Callable target or function pointer. \
   * @param ctx Caller-owned callback context. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE NAME NAME##_make(NAME##_fn fn, void* ctx); \
  /** \
   * @brief Run the generated valid operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @return `true` when the documented condition holds; otherwise `false`. \
   */ \
  SSTL_C_INLINE bool NAME##_valid(const NAME* f); \
  /** \
   * @brief Run the generated call operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @param a0 First callable argument. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE R NAME##_call(const NAME* f, A0 a0);

/** @def SSTL_FUNCTION1_DEFINE
 * @brief Define the typed C SSTL API family generated by `SSTL_FUNCTION1_DEFINE`.
 */
#define SSTL_FUNCTION1_DEFINE(NAME, R, A0) \
  /** \
   * @brief Run the generated make operation for this typed SSTL family. \
   * @param fn Callable target or function pointer. \
   * @param ctx Caller-owned callback context. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE NAME NAME##_make(NAME##_fn fn, void* ctx) { NAME f; f.fn = fn; f.ctx = ctx; return f; } \
  /** \
   * @brief Run the generated valid operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @return `true` when the documented condition holds; otherwise `false`. \
   */ \
  SSTL_C_INLINE bool NAME##_valid(const NAME* f) { return f->fn != 0; } \
  /** \
   * @brief Run the generated call operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @param a0 First callable argument. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE R NAME##_call(const NAME* f, A0 a0) { return f->fn(f->ctx, a0); }

/** @def SSTL_FUNCTION2_DECLARE
 * @brief Declare a typed C callable wrapper for functions with two arguments.
 */
#define SSTL_FUNCTION2_DECLARE(NAME, R, A0, A1) \
  typedef R (*NAME##_fn)(void* ctx, A0 a0, A1 a1); \
  typedef struct NAME { NAME##_fn fn; /**< @brief Callable target pointer, or null when invalid. */ void* ctx; /**< @brief Caller-owned context pointer passed to the target on every invocation. */ } NAME; \
  /** \
   * @brief Run the generated make operation for this typed SSTL family. \
   * @param fn Callable target or function pointer. \
   * @param ctx Caller-owned callback context. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE NAME NAME##_make(NAME##_fn fn, void* ctx); \
  /** \
   * @brief Run the generated valid operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @return `true` when the documented condition holds; otherwise `false`. \
   */ \
  SSTL_C_INLINE bool NAME##_valid(const NAME* f); \
  /** \
   * @brief Run the generated call operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @param a0 First callable argument. \
   * @param a1 Second callable argument. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE R NAME##_call(const NAME* f, A0 a0, A1 a1);

/** @def SSTL_FUNCTION2_DEFINE
 * @brief Define a typed C callable wrapper for functions with two arguments.
 */
#define SSTL_FUNCTION2_DEFINE(NAME, R, A0, A1) \
  /** \
   * @brief Run the generated make operation for this typed SSTL family. \
   * @param fn Callable target or function pointer. \
   * @param ctx Caller-owned callback context. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE NAME NAME##_make(NAME##_fn fn, void* ctx) { NAME f; f.fn = fn; f.ctx = ctx; return f; } \
  /** \
   * @brief Run the generated valid operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @return `true` when the documented condition holds; otherwise `false`. \
   */ \
  SSTL_C_INLINE bool NAME##_valid(const NAME* f) { return f->fn != 0; } \
  /** \
   * @brief Run the generated call operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @param a0 First callable argument. \
   * @param a1 Second callable argument. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE R NAME##_call(const NAME* f, A0 a0, A1 a1) { return f->fn(f->ctx, a0, a1); }

/** @def SSTL_FUNCTION3_DECLARE
 * @brief Declare a typed C callable wrapper for functions with three arguments.
 */
#define SSTL_FUNCTION3_DECLARE(NAME, R, A0, A1, A2) \
  typedef R (*NAME##_fn)(void* ctx, A0 a0, A1 a1, A2 a2); \
  typedef struct NAME { NAME##_fn fn; /**< @brief Callable target pointer, or null when invalid. */ void* ctx; /**< @brief Caller-owned context pointer passed to the target on every invocation. */ } NAME; \
  /** \
   * @brief Run the generated make operation for this typed SSTL family. \
   * @param fn Callable target or function pointer. \
   * @param ctx Caller-owned callback context. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE NAME NAME##_make(NAME##_fn fn, void* ctx); \
  /** \
   * @brief Run the generated valid operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @return `true` when the documented condition holds; otherwise `false`. \
   */ \
  SSTL_C_INLINE bool NAME##_valid(const NAME* f); \
  /** \
   * @brief Run the generated call operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @param a0 First callable argument. \
   * @param a1 Second callable argument. \
   * @param a2 Third callable argument. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE R NAME##_call(const NAME* f, A0 a0, A1 a1, A2 a2);

/** @def SSTL_FUNCTION3_DEFINE
 * @brief Define a typed C callable wrapper for functions with three arguments.
 */
#define SSTL_FUNCTION3_DEFINE(NAME, R, A0, A1, A2) \
  /** \
   * @brief Run the generated make operation for this typed SSTL family. \
   * @param fn Callable target or function pointer. \
   * @param ctx Caller-owned callback context. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE NAME NAME##_make(NAME##_fn fn, void* ctx) { NAME f; f.fn = fn; f.ctx = ctx; return f; } \
  /** \
   * @brief Run the generated valid operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @return `true` when the documented condition holds; otherwise `false`. \
   */ \
  SSTL_C_INLINE bool NAME##_valid(const NAME* f) { return f->fn != 0; } \
  /** \
   * @brief Run the generated call operation for this typed SSTL family. \
   * @param f Callable object or function wrapper. \
   * @param a0 First callable argument. \
   * @param a1 Second callable argument. \
   * @param a2 Third callable argument. \
   * @return Result described by the function brief. \
   */ \
  SSTL_C_INLINE R NAME##_call(const NAME* f, A0 a0, A1 a1, A2 a2) { return f->fn(f->ctx, a0, a1, a2); }

#endif

