/**
 * @file sstl_set.h
 * @brief C99 fixed-capacity ordered set backed by a comparator-driven static red/black node pool.
 */
#ifndef SSTL_C_SET_H
/** @def SSTL_C_SET_H
 * @brief Include guard for sstl_set.h.
 */
#define SSTL_C_SET_H
#include "sstl_algorithm.h"

/** @def SSTL_SET_DECLARE
 * @brief Declare the typed C SSTL API family generated by `SSTL_SET_DECLARE`.
 * @param NAME Public function/type prefix.
 * @param K Key type stored by value.
 * @param CAP Fixed compile-time key capacity.
 * @param CMP Three-way comparator with signature compatible with `int cmp(const void*, const void*)`.
 */
#define SSTL_SET_DECLARE(NAME, K, CAP, CMP) \
  typedef int NAME##_iterator; \
  typedef struct NAME##_node { K key; /**< @brief Stored set key. */ int parent; /**< @brief Parent node index, or -1. */ int left; /**< @brief Left child node index, or -1. */ int right; /**< @brief Right child node index, or -1. */ int next_free; /**< @brief Next free node index while unused. */ bool red; /**< @brief Red/black color bit; true means red. */ bool used; /**< @brief Whether this node currently owns a key. */ } NAME##_node; \
  typedef struct NAME { NAME##_node nodes[(CAP) == 0 ? 1 : (CAP)]; /**< @brief Static red/black node pool. */ int root; /**< @brief Root node index, or -1 when empty. */ int free_head; /**< @brief First free node index, or -1. */ size_t size; /**< @brief Number of live keys. */ } NAME; \
  /** @brief Initialize the set to empty state. */ SSTL_C_INLINE void NAME##_init(NAME* s); \
  /** @brief Return the number of stored keys. */ SSTL_C_INLINE size_t NAME##_size(const NAME* s); \
  /** @brief Return the fixed key capacity. */ SSTL_C_INLINE size_t NAME##_capacity(const NAME* s); \
  /** @brief Report whether no keys are live. */ SSTL_C_INLINE bool NAME##_empty(const NAME* s); \
  /** @brief Report whether capacity is exhausted. */ SSTL_C_INLINE bool NAME##_full(const NAME* s); \
  /** @brief Remove every key and rebuild the free-list. */ SSTL_C_INLINE void NAME##_clear(NAME* s); \
  /** @brief Exchange two sets of the same generated type. */ SSTL_C_INLINE void NAME##_swap(NAME* a, NAME* b); \
  /** @brief Insert a key when absent. */ SSTL_C_INLINE bool NAME##_insert(NAME* s, K key); \
  /** @brief Find a key and return a pointer to it, or null. */ SSTL_C_INLINE K* NAME##_find(NAME* s, K key); \
  /** @brief Return whether the key is present. */ SSTL_C_INLINE size_t NAME##_count(const NAME* s, K key); \
  /** @brief Return an iterator to the first key not less than `key`. */ SSTL_C_INLINE NAME##_iterator NAME##_lower_bound(const NAME* s, K key); \
  /** @brief Return an iterator to the first key greater than `key`. */ SSTL_C_INLINE NAME##_iterator NAME##_upper_bound(const NAME* s, K key); \
  /** @brief Return the lower-bound side of the equal range. */ SSTL_C_INLINE NAME##_iterator NAME##_equal_range_first(const NAME* s, K key); \
  /** @brief Return the upper-bound side of the equal range. */ SSTL_C_INLINE NAME##_iterator NAME##_equal_range_second(const NAME* s, K key); \
  /** @brief Erase one key and return the number removed. */ SSTL_C_INLINE size_t NAME##_erase(NAME* s, K key); \
  /** @brief Return an iterator to the smallest key. */ SSTL_C_INLINE NAME##_iterator NAME##_begin(const NAME* s); \
  /** @brief Return the end iterator. */ SSTL_C_INLINE NAME##_iterator NAME##_end(const NAME* s); \
  /** @brief Advance to the next ordered node. */ SSTL_C_INLINE NAME##_iterator NAME##_next(const NAME* s, NAME##_iterator it); \
  /** @brief Move to the previous ordered node, supporting prev(end()). */ SSTL_C_INLINE NAME##_iterator NAME##_prev(const NAME* s, NAME##_iterator it); \
  /** @brief Return a pointer to the key named by `it`, or null. */ SSTL_C_INLINE K* NAME##_at(NAME* s, NAME##_iterator it); \
  /** @brief Return a pointer to the key named by `it`, or null. */ SSTL_C_INLINE K* NAME##_deref(NAME* s, NAME##_iterator it);

/** @def SSTL_SET_DEFINE
 * @brief Define the typed C SSTL API family generated by `SSTL_SET_DEFINE`.
 * @param NAME Public function/type prefix.
 * @param K Key type stored by value.
 * @param CAP Fixed compile-time key capacity.
 * @param CMP Three-way comparator with signature compatible with `int cmp(const void*, const void*)`.
 */
#define SSTL_SET_DEFINE(NAME, K, CAP, CMP) \
  /** @brief Initialize the set to empty state. */ SSTL_C_INLINE void NAME##_init(NAME* s) { size_t i; s->root = -1; s->free_head = (CAP) == 0 ? -1 : 0; s->size = 0u; for (i = 0u; i != (size_t)(CAP); ++i) { s->nodes[i].parent = -1; s->nodes[i].left = -1; s->nodes[i].right = -1; s->nodes[i].next_free = (i + 1u < (size_t)(CAP)) ? (int)(i + 1u) : -1; s->nodes[i].red = false; s->nodes[i].used = false; } } \
  /** @brief Return the number of stored keys. */ SSTL_C_INLINE size_t NAME##_size(const NAME* s) { return s->size; } \
  /** @brief Return the fixed key capacity. */ SSTL_C_INLINE size_t NAME##_capacity(const NAME* s) { (void)s; return (size_t)(CAP); } \
  /** @brief Report whether no keys are live. */ SSTL_C_INLINE bool NAME##_empty(const NAME* s) { return s->size == 0u; } \
  /** @brief Report whether capacity is exhausted. */ SSTL_C_INLINE bool NAME##_full(const NAME* s) { return s->size == (size_t)(CAP); } \
  /** @brief Remove every key and rebuild the free-list. */ SSTL_C_INLINE void NAME##_clear(NAME* s) { NAME##_init(s); } \
  /** @brief Exchange two sets of the same generated type. */ SSTL_C_INLINE void NAME##_swap(NAME* a, NAME* b) { NAME tmp = *a; *a = *b; *b = tmp; } \
  /** @brief Return whether a node index names a red node. */ SSTL_C_INLINE bool NAME##_is_red(const NAME* s, int n) { return n >= 0 && s->nodes[(size_t)n].red; } \
  /** @brief Return the leftmost node in a subtree. */ SSTL_C_INLINE int NAME##_minimum(const NAME* s, int n) { if (n < 0) return -1; while (s->nodes[(size_t)n].left >= 0) n = s->nodes[(size_t)n].left; return n; } \
  /** @brief Return the rightmost node in a subtree. */ SSTL_C_INLINE int NAME##_maximum(const NAME* s, int n) { if (n < 0) return -1; while (s->nodes[(size_t)n].right >= 0) n = s->nodes[(size_t)n].right; return n; } \
  /** @brief Return the ordered successor of a node. */ SSTL_C_INLINE int NAME##_successor(const NAME* s, int n) { int p; if (n < 0) return -1; if (s->nodes[(size_t)n].right >= 0) return NAME##_minimum(s, s->nodes[(size_t)n].right); p = s->nodes[(size_t)n].parent; while (p >= 0 && n == s->nodes[(size_t)p].right) { n = p; p = s->nodes[(size_t)p].parent; } return p; } \
  /** @brief Return the ordered predecessor of a node, or the last node for end. */ SSTL_C_INLINE int NAME##_predecessor(const NAME* s, int n) { int p; if (n < 0) return n == -1 ? NAME##_maximum(s, s->root) : -1; if ((size_t)n >= (size_t)(CAP) || !s->nodes[(size_t)n].used) return -1; if (s->nodes[(size_t)n].left >= 0) return NAME##_maximum(s, s->nodes[(size_t)n].left); p = s->nodes[(size_t)n].parent; while (p >= 0 && n == s->nodes[(size_t)p].left) { n = p; p = s->nodes[(size_t)p].parent; } return p; } \
  /** @brief Rotate a subtree left around node `x`. */ SSTL_C_INLINE void NAME##_rotate_left(NAME* s, int x) { int y = s->nodes[(size_t)x].right; s->nodes[(size_t)x].right = s->nodes[(size_t)y].left; if (s->nodes[(size_t)y].left >= 0) s->nodes[(size_t)s->nodes[(size_t)y].left].parent = x; s->nodes[(size_t)y].parent = s->nodes[(size_t)x].parent; if (s->nodes[(size_t)x].parent < 0) s->root = y; else if (x == s->nodes[(size_t)s->nodes[(size_t)x].parent].left) s->nodes[(size_t)s->nodes[(size_t)x].parent].left = y; else s->nodes[(size_t)s->nodes[(size_t)x].parent].right = y; s->nodes[(size_t)y].left = x; s->nodes[(size_t)x].parent = y; } \
  /** @brief Rotate a subtree right around node `x`. */ SSTL_C_INLINE void NAME##_rotate_right(NAME* s, int x) { int y = s->nodes[(size_t)x].left; s->nodes[(size_t)x].left = s->nodes[(size_t)y].right; if (s->nodes[(size_t)y].right >= 0) s->nodes[(size_t)s->nodes[(size_t)y].right].parent = x; s->nodes[(size_t)y].parent = s->nodes[(size_t)x].parent; if (s->nodes[(size_t)x].parent < 0) s->root = y; else if (x == s->nodes[(size_t)s->nodes[(size_t)x].parent].right) s->nodes[(size_t)s->nodes[(size_t)x].parent].right = y; else s->nodes[(size_t)s->nodes[(size_t)x].parent].left = y; s->nodes[(size_t)y].right = x; s->nodes[(size_t)x].parent = y; } \
  /** @brief Restore red/black insert invariants after adding `z`. */ SSTL_C_INLINE void NAME##_fix_after_insert(NAME* s, int z) { while (z != s->root && NAME##_is_red(s, s->nodes[(size_t)z].parent)) { int p = s->nodes[(size_t)z].parent; int g = s->nodes[(size_t)p].parent; if (p == s->nodes[(size_t)g].left) { int u = s->nodes[(size_t)g].right; if (NAME##_is_red(s, u)) { s->nodes[(size_t)p].red = false; s->nodes[(size_t)u].red = false; s->nodes[(size_t)g].red = true; z = g; } else { if (z == s->nodes[(size_t)p].right) { z = p; NAME##_rotate_left(s, z); p = s->nodes[(size_t)z].parent; g = s->nodes[(size_t)p].parent; } s->nodes[(size_t)p].red = false; s->nodes[(size_t)g].red = true; NAME##_rotate_right(s, g); } } else { int u = s->nodes[(size_t)g].left; if (NAME##_is_red(s, u)) { s->nodes[(size_t)p].red = false; s->nodes[(size_t)u].red = false; s->nodes[(size_t)g].red = true; z = g; } else { if (z == s->nodes[(size_t)p].left) { z = p; NAME##_rotate_right(s, z); p = s->nodes[(size_t)z].parent; g = s->nodes[(size_t)p].parent; } s->nodes[(size_t)p].red = false; s->nodes[(size_t)g].red = true; NAME##_rotate_left(s, g); } } } if (s->root >= 0) s->nodes[(size_t)s->root].red = false; } \
  /** @brief Find a node index by key using the generated comparator hook. */ SSTL_C_INLINE int NAME##_find_node(const NAME* s, K key) { int cur = s->root; while (cur >= 0) { K node_key = s->nodes[(size_t)cur].key; int cmp = (CMP)((const void*)&key, (const void*)&node_key); if (cmp < 0) cur = s->nodes[(size_t)cur].left; else if (cmp > 0) cur = s->nodes[(size_t)cur].right; else return cur; } return -1; } \
  /** @brief Return the first node whose key is not less than `key`. */ SSTL_C_INLINE int NAME##_lower_bound_node(const NAME* s, K key) { int cur = s->root; int best = -1; while (cur >= 0) { K node_key = s->nodes[(size_t)cur].key; int cmp = (CMP)((const void*)&node_key, (const void*)&key); if (cmp < 0) cur = s->nodes[(size_t)cur].right; else { best = cur; cur = s->nodes[(size_t)cur].left; } } return best; } \
  /** @brief Return the first node whose key is greater than `key`. */ SSTL_C_INLINE int NAME##_upper_bound_node(const NAME* s, K key) { int cur = s->root; int best = -1; while (cur >= 0) { K node_key = s->nodes[(size_t)cur].key; int cmp = (CMP)((const void*)&key, (const void*)&node_key); if (cmp < 0) { best = cur; cur = s->nodes[(size_t)cur].left; } else cur = s->nodes[(size_t)cur].right; } return best; } \
  /** @brief Allocate a free tree node and store `key` in it. */ SSTL_C_INLINE int NAME##_allocate_node(NAME* s, K key) { int slot; if (s->free_head < 0) return -1; slot = s->free_head; s->free_head = s->nodes[(size_t)slot].next_free; s->nodes[(size_t)slot].key = key; s->nodes[(size_t)slot].parent = -1; s->nodes[(size_t)slot].left = -1; s->nodes[(size_t)slot].right = -1; s->nodes[(size_t)slot].next_free = -1; s->nodes[(size_t)slot].red = true; s->nodes[(size_t)slot].used = true; return slot; } \
  /** @brief Return a node to the free-list. */ SSTL_C_INLINE void NAME##_release_node(NAME* s, int slot) { s->nodes[(size_t)slot].used = false; s->nodes[(size_t)slot].parent = -1; s->nodes[(size_t)slot].left = -1; s->nodes[(size_t)slot].right = -1; s->nodes[(size_t)slot].red = false; s->nodes[(size_t)slot].next_free = s->free_head; s->free_head = slot; } \
  /** @brief Set a node color when the index names a live tree node. */ SSTL_C_INLINE void NAME##_set_red(NAME* s, int n, bool red) { if (n >= 0) s->nodes[(size_t)n].red = red; } \
  /** @brief Return a node parent index or -1 for a null node. */ SSTL_C_INLINE int NAME##_parent_of(const NAME* s, int n) { return n >= 0 ? s->nodes[(size_t)n].parent : -1; } \
  /** @brief Return a node left-child index or -1 for a null node. */ SSTL_C_INLINE int NAME##_left_of(const NAME* s, int n) { return n >= 0 ? s->nodes[(size_t)n].left : -1; } \
  /** @brief Return a node right-child index or -1 for a null node. */ SSTL_C_INLINE int NAME##_right_of(const NAME* s, int n) { return n >= 0 ? s->nodes[(size_t)n].right : -1; } \
  /** @brief Replace one subtree root with another during erase. */ SSTL_C_INLINE void NAME##_transplant(NAME* s, int old_root, int new_root) { int parent = s->nodes[(size_t)old_root].parent; if (parent < 0) s->root = new_root; else if (old_root == s->nodes[(size_t)parent].left) s->nodes[(size_t)parent].left = new_root; else s->nodes[(size_t)parent].right = new_root; if (new_root >= 0) s->nodes[(size_t)new_root].parent = parent; } \
  /** @brief Restore red/black invariants after removing a black node. */ SSTL_C_INLINE void NAME##_fix_after_erase(NAME* s, int x, int parent) { while (x != s->root && !NAME##_is_red(s, x)) { if (parent < 0) break; if (x == s->nodes[(size_t)parent].left) { int sibling = s->nodes[(size_t)parent].right; if (NAME##_is_red(s, sibling)) { NAME##_set_red(s, sibling, false); NAME##_set_red(s, parent, true); NAME##_rotate_left(s, parent); sibling = s->nodes[(size_t)parent].right; } if (!NAME##_is_red(s, NAME##_left_of(s, sibling)) && !NAME##_is_red(s, NAME##_right_of(s, sibling))) { NAME##_set_red(s, sibling, true); x = parent; parent = NAME##_parent_of(s, x); } else { if (!NAME##_is_red(s, NAME##_right_of(s, sibling))) { NAME##_set_red(s, NAME##_left_of(s, sibling), false); NAME##_set_red(s, sibling, true); NAME##_rotate_right(s, sibling); sibling = s->nodes[(size_t)parent].right; } NAME##_set_red(s, sibling, NAME##_is_red(s, parent)); NAME##_set_red(s, parent, false); NAME##_set_red(s, NAME##_right_of(s, sibling), false); NAME##_rotate_left(s, parent); x = s->root; parent = -1; } } else { int sibling = s->nodes[(size_t)parent].left; if (NAME##_is_red(s, sibling)) { NAME##_set_red(s, sibling, false); NAME##_set_red(s, parent, true); NAME##_rotate_right(s, parent); sibling = s->nodes[(size_t)parent].left; } if (!NAME##_is_red(s, NAME##_right_of(s, sibling)) && !NAME##_is_red(s, NAME##_left_of(s, sibling))) { NAME##_set_red(s, sibling, true); x = parent; parent = NAME##_parent_of(s, x); } else { if (!NAME##_is_red(s, NAME##_left_of(s, sibling))) { NAME##_set_red(s, NAME##_right_of(s, sibling), false); NAME##_set_red(s, sibling, true); NAME##_rotate_left(s, sibling); sibling = s->nodes[(size_t)parent].left; } NAME##_set_red(s, sibling, NAME##_is_red(s, parent)); NAME##_set_red(s, parent, false); NAME##_set_red(s, NAME##_left_of(s, sibling), false); NAME##_rotate_right(s, parent); x = s->root; parent = -1; } } } NAME##_set_red(s, x, false); } \
  /** @brief Erase a tree node in place and preserve red/black structure. */ SSTL_C_INLINE void NAME##_erase_node(NAME* s, int z) { int y = z; int x = -1; int parent = -1; bool y_was_red = s->nodes[(size_t)y].red; if (s->nodes[(size_t)z].left < 0) { x = s->nodes[(size_t)z].right; parent = s->nodes[(size_t)z].parent; NAME##_transplant(s, z, x); } else if (s->nodes[(size_t)z].right < 0) { x = s->nodes[(size_t)z].left; parent = s->nodes[(size_t)z].parent; NAME##_transplant(s, z, x); } else { y = NAME##_successor(s, z); y_was_red = s->nodes[(size_t)y].red; x = s->nodes[(size_t)y].right; if (s->nodes[(size_t)y].parent == z) { parent = y; } else { parent = s->nodes[(size_t)y].parent; NAME##_transplant(s, y, x); s->nodes[(size_t)y].right = s->nodes[(size_t)z].right; s->nodes[(size_t)s->nodes[(size_t)y].right].parent = y; } NAME##_transplant(s, z, y); s->nodes[(size_t)y].left = s->nodes[(size_t)z].left; s->nodes[(size_t)s->nodes[(size_t)y].left].parent = y; s->nodes[(size_t)y].red = s->nodes[(size_t)z].red; } if (!y_was_red) NAME##_fix_after_erase(s, x, parent); NAME##_release_node(s, z); --s->size; if (s->size == 0u) s->root = -1; } \
  /** @brief Insert a key when absent using the comparator hook. */ SSTL_C_INLINE bool NAME##_insert(NAME* s, K key) { int parent = -1; int cur = s->root; bool went_left = false; int slot; while (cur >= 0) { int cmp; parent = cur; cmp = (CMP)((const void*)&key, (const void*)&s->nodes[(size_t)cur].key); if (cmp < 0) { went_left = true; cur = s->nodes[(size_t)cur].left; } else if (cmp > 0) { went_left = false; cur = s->nodes[(size_t)cur].right; } else return false; } if (s->size == (size_t)(CAP)) { SSTL_C_PANIC("set full"); return false; } slot = NAME##_allocate_node(s, key); if (slot < 0) return false; s->nodes[(size_t)slot].parent = parent; if (parent < 0) s->root = slot; else if (went_left) s->nodes[(size_t)parent].left = slot; else s->nodes[(size_t)parent].right = slot; ++s->size; NAME##_fix_after_insert(s, slot); return true; } \
  /** @brief Find a key and return a pointer to it, or null. */ SSTL_C_INLINE K* NAME##_find(NAME* s, K key) { int n = NAME##_find_node(s, key); return n >= 0 ? &s->nodes[(size_t)n].key : 0; } \
  /** @brief Return whether the key is present. */ SSTL_C_INLINE size_t NAME##_count(const NAME* s, K key) { return NAME##_find_node(s, key) >= 0 ? 1u : 0u; } \
  /** @brief Return an iterator to the first key not less than `key`. */ SSTL_C_INLINE NAME##_iterator NAME##_lower_bound(const NAME* s, K key) { return NAME##_lower_bound_node(s, key); } \
  /** @brief Return an iterator to the first key greater than `key`. */ SSTL_C_INLINE NAME##_iterator NAME##_upper_bound(const NAME* s, K key) { return NAME##_upper_bound_node(s, key); } \
  /** @brief Return the lower-bound side of the equal range. */ SSTL_C_INLINE NAME##_iterator NAME##_equal_range_first(const NAME* s, K key) { return NAME##_lower_bound(s, key); } \
  /** @brief Return the upper-bound side of the equal range. */ SSTL_C_INLINE NAME##_iterator NAME##_equal_range_second(const NAME* s, K key) { return NAME##_upper_bound(s, key); } \
  /** @brief Erase one key in place, returning whether it was present. */ SSTL_C_INLINE size_t NAME##_erase(NAME* s, K key) { int node = NAME##_find_node(s, key); if (node < 0) return 0u; NAME##_erase_node(s, node); return 1u; } \
  /** @brief Return an iterator to the smallest key. */ SSTL_C_INLINE NAME##_iterator NAME##_begin(const NAME* s) { return NAME##_minimum(s, s->root); } \
  /** @brief Return the end iterator. */ SSTL_C_INLINE NAME##_iterator NAME##_end(const NAME* s) { (void)s; return -1; } \
  /** @brief Advance to the next ordered node. */ SSTL_C_INLINE NAME##_iterator NAME##_next(const NAME* s, NAME##_iterator it) { return NAME##_successor(s, it); } \
  /** @brief Move to the previous ordered node, supporting prev(end()). */ SSTL_C_INLINE NAME##_iterator NAME##_prev(const NAME* s, NAME##_iterator it) { return NAME##_predecessor(s, it); } \
  /** @brief Return a pointer to the key named by `it`, or null. */ SSTL_C_INLINE K* NAME##_at(NAME* s, NAME##_iterator it) { return (it >= 0 && (size_t)it < (size_t)(CAP) && s->nodes[(size_t)it].used) ? &s->nodes[(size_t)it].key : 0; } \
  /** @brief Return a pointer to the key named by `it`, or null. */ SSTL_C_INLINE K* NAME##_deref(NAME* s, NAME##_iterator it) { return NAME##_at(s, it); }

#endif

