/**
 * @file sstl_variant.h
 * @brief C99 SSTL public header with static, allocation-free API surface.
 *
 * The declarations in this file are part of the local SSTL contract. They are
 * documented for Doxygen consumers and for maintainers reading the headers
 * directly. Keep behavior aligned with the SSTL public contract and tests,
 * and avoid introducing hosted STL dependencies into implementation
 * headers.
 */
#ifndef SSTL_C_VARIANT_H
/** @def SSTL_C_VARIANT_H
 * @brief Include guard for sstl_variant.h.
 */
#define SSTL_C_VARIANT_H
#include "sstl_config.h"

/** @def SSTL_VARIANT2_DECLARE
 * @brief Declare the typed C SSTL API family generated by `SSTL_VARIANT2_DECLARE`.
 */
#define SSTL_VARIANT2_DECLARE(NAME, A, B) \
  typedef struct NAME { unsigned index; /**< @brief Active alternative index: 0 for a, 1 for b. */ union { A a; /**< @brief Storage for alternative 0. */ B b; /**< @brief Storage for alternative 1. */ } value; /**< @brief Union storage for all alternatives. */ } NAME; \
  /** \
   * @brief Run the generated set0 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param a First operand or first range start. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set0(NAME* v, A a); \
  /** \
   * @brief Run the generated set1 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param b Second operand or second range start. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set1(NAME* v, B b); \
  /** \
   * @brief Run the generated index operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED unsigned NAME##_index(const NAME* v); \
  /** \
   * @brief Run the generated get0 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED A* NAME##_get0(NAME* v); \
  /** \
   * @brief Run the generated get1 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED B* NAME##_get1(NAME* v);

/** @def SSTL_VARIANT2_DEFINE
 * @brief Define the typed C SSTL API family generated by `SSTL_VARIANT2_DEFINE`.
 */
#define SSTL_VARIANT2_DEFINE(NAME, A, B) \
  /** \
   * @brief Run the generated set0 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param a First operand or first range start. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set0(NAME* v, A a) { v->index = 0u; v->value.a = a; } \
  /** \
   * @brief Run the generated set1 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param b Second operand or second range start. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set1(NAME* v, B b) { v->index = 1u; v->value.b = b; } \
  /** \
   * @brief Run the generated index operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED unsigned NAME##_index(const NAME* v) { return v->index; } \
  /** \
   * @brief Run the generated get0 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED A* NAME##_get0(NAME* v) { return v->index == 0u ? &v->value.a : 0; } \
  /** \
   * @brief Run the generated get1 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED B* NAME##_get1(NAME* v) { return v->index == 1u ? &v->value.b : 0; }

/** @def SSTL_VARIANT3_DECLARE
 * @brief Declare a typed C tagged union with three alternatives.
 */
#define SSTL_VARIANT3_DECLARE(NAME, A, B, C) \
  typedef struct NAME { unsigned index; /**< @brief Active alternative index: 0 for a, 1 for b, 2 for c. */ union { A a; /**< @brief Storage for alternative 0. */ B b; /**< @brief Storage for alternative 1. */ C c; /**< @brief Storage for alternative 2. */ } value; /**< @brief Union storage for all alternatives. */ } NAME; \
  /** \
   * @brief Run the generated set0 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param a First operand or first range start. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set0(NAME* v, A a); \
  /** \
   * @brief Run the generated set1 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param b Second operand or second range start. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set1(NAME* v, B b); \
  /** \
   * @brief Run the generated set2 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param c Character value. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set2(NAME* v, C c); \
  /** \
   * @brief Run the generated index operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED unsigned NAME##_index(const NAME* v); \
  /** \
   * @brief Run the generated get0 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED A* NAME##_get0(NAME* v); \
  /** \
   * @brief Run the generated get1 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED B* NAME##_get1(NAME* v); \
  /** \
   * @brief Run the generated get2 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED C* NAME##_get2(NAME* v);

/** @def SSTL_VARIANT3_DEFINE
 * @brief Define a typed C tagged union with three alternatives.
 */
#define SSTL_VARIANT3_DEFINE(NAME, A, B, C) \
  /** \
   * @brief Run the generated set0 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param a First operand or first range start. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set0(NAME* v, A a) { v->index = 0u; v->value.a = a; } \
  /** \
   * @brief Run the generated set1 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param b Second operand or second range start. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set1(NAME* v, B b) { v->index = 1u; v->value.b = b; } \
  /** \
   * @brief Run the generated set2 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param c Character value. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set2(NAME* v, C c) { v->index = 2u; v->value.c = c; } \
  /** \
   * @brief Run the generated index operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED unsigned NAME##_index(const NAME* v) { return v->index; } \
  /** \
   * @brief Run the generated get0 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED A* NAME##_get0(NAME* v) { return v->index == 0u ? &v->value.a : 0; } \
  /** \
   * @brief Run the generated get1 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED B* NAME##_get1(NAME* v) { return v->index == 1u ? &v->value.b : 0; } \
  /** \
   * @brief Run the generated get2 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED C* NAME##_get2(NAME* v) { return v->index == 2u ? &v->value.c : 0; }

/** @def SSTL_VARIANT4_DECLARE
 * @brief Declare a typed C tagged union with four alternatives.
 */
#define SSTL_VARIANT4_DECLARE(NAME, A, B, C, D) \
  typedef struct NAME { unsigned index; /**< @brief Active alternative index: 0 for a, 1 for b, 2 for c, 3 for d. */ union { A a; /**< @brief Storage for alternative 0. */ B b; /**< @brief Storage for alternative 1. */ C c; /**< @brief Storage for alternative 2. */ D d; /**< @brief Storage for alternative 3. */ } value; /**< @brief Union storage for all alternatives. */ } NAME; \
  /** \
   * @brief Run the generated set0 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param a First operand or first range start. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set0(NAME* v, A a); \
  /** \
   * @brief Run the generated set1 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param b Second operand or second range start. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set1(NAME* v, B b); \
  /** \
   * @brief Run the generated set2 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param c Character value. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set2(NAME* v, C c); \
  /** \
   * @brief Run the generated set3 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param d Deque instance. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set3(NAME* v, D d); \
  /** \
   * @brief Run the generated index operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED unsigned NAME##_index(const NAME* v); \
  /** \
   * @brief Run the generated get0 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED A* NAME##_get0(NAME* v); \
  /** \
   * @brief Run the generated get1 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED B* NAME##_get1(NAME* v); \
  /** \
   * @brief Run the generated get2 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED C* NAME##_get2(NAME* v); \
  /** \
   * @brief Run the generated get3 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED D* NAME##_get3(NAME* v);

/** @def SSTL_VARIANT4_DEFINE
 * @brief Define a typed C tagged union with four alternatives.
 */
#define SSTL_VARIANT4_DEFINE(NAME, A, B, C, D) \
  /** \
   * @brief Run the generated set0 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param a First operand or first range start. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set0(NAME* v, A a) { v->index = 0u; v->value.a = a; } \
  /** \
   * @brief Run the generated set1 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param b Second operand or second range start. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set1(NAME* v, B b) { v->index = 1u; v->value.b = b; } \
  /** \
   * @brief Run the generated set2 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param c Character value. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set2(NAME* v, C c) { v->index = 2u; v->value.c = c; } \
  /** \
   * @brief Run the generated set3 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @param d Deque instance. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set3(NAME* v, D d) { v->index = 3u; v->value.d = d; } \
  /** \
   * @brief Run the generated index operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED unsigned NAME##_index(const NAME* v) { return v->index; } \
  /** \
   * @brief Run the generated get0 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED A* NAME##_get0(NAME* v) { return v->index == 0u ? &v->value.a : 0; } \
  /** \
   * @brief Run the generated get1 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED B* NAME##_get1(NAME* v) { return v->index == 1u ? &v->value.b : 0; } \
  /** \
   * @brief Run the generated get2 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED C* NAME##_get2(NAME* v) { return v->index == 2u ? &v->value.c : 0; } \
  /** \
   * @brief Run the generated get3 operation for this typed SSTL family. \
   * @param v Generated object or variant instance. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED D* NAME##_get3(NAME* v) { return v->index == 3u ? &v->value.d : 0; }

#endif

