/**
 * @file sstl_map.h
 * @brief C99 fixed-capacity ordered map backed by a static red/black node pool.
 *
 * Generated map families store nodes in object-owned arrays and search through
 * tree links. The public API remains key-oriented for C callers while the
 * internal structure matches the ordered-node container contract. Each
 * generated family receives a three-way comparator hook so callers can use
 * scalar keys, pointer keys, or struct keys without relying on C operators.
 */
#ifndef SSTL_C_MAP_H
/** @def SSTL_C_MAP_H
 * @brief Include guard for sstl_map.h.
 */
#define SSTL_C_MAP_H
#include "sstl_algorithm.h"

/** @def SSTL_MAP_DECLARE
 * @brief Declare the typed C SSTL API family generated by `SSTL_MAP_DECLARE`.
 * @param NAME Public function/type prefix.
 * @param K Key type stored by value.
 * @param V Mapped value type stored by value.
 * @param CAP Fixed compile-time entry capacity.
 * @param CMP Three-way comparator with signature compatible with `int cmp(const void*, const void*)`.
 */
#define SSTL_MAP_DECLARE(NAME, K, V, CAP, CMP) \
  typedef int NAME##_iterator; \
  typedef struct NAME##_pair { K key; /**< @brief Stored key for this map entry. */ V value; /**< @brief Stored value associated with key. */ } NAME##_pair; \
  typedef struct NAME##_node { NAME##_pair entry; /**< @brief Stored key/value pair. */ int parent; /**< @brief Parent node index, or -1. */ int left; /**< @brief Left child node index, or -1. */ int right; /**< @brief Right child node index, or -1. */ int next_free; /**< @brief Next free node index while unused. */ bool red; /**< @brief Red/black color bit; true means red. */ bool used; /**< @brief Whether this node currently owns an entry. */ } NAME##_node; \
  typedef struct NAME { NAME##_node nodes[(CAP) == 0 ? 1 : (CAP)]; /**< @brief Static red/black node pool. */ int root; /**< @brief Root node index, or -1 when empty. */ int free_head; /**< @brief First free node index, or -1. */ size_t size; /**< @brief Number of live entries. */ } NAME; \
  /** @brief Initialize the map to empty state. */ SSTL_C_INLINE void NAME##_init(NAME* m); \
  /** @brief Return the number of stored entries. */ SSTL_C_INLINE size_t NAME##_size(const NAME* m); \
  /** @brief Return the fixed entry capacity. */ SSTL_C_INLINE size_t NAME##_capacity(const NAME* m); \
  /** @brief Report whether no entries are live. */ SSTL_C_INLINE bool NAME##_empty(const NAME* m); \
  /** @brief Report whether capacity is exhausted. */ SSTL_C_INLINE bool NAME##_full(const NAME* m); \
  /** @brief Remove every entry and rebuild the free-list. */ SSTL_C_INLINE void NAME##_clear(NAME* m); \
  /** @brief Exchange two maps of the same generated type. */ SSTL_C_INLINE void NAME##_swap(NAME* a, NAME* b); \
  /** @brief Insert a key/value pair when the key is absent. */ SSTL_C_INLINE bool NAME##_insert(NAME* m, K key, V value); \
  /** @brief Erase one key and return the number removed. */ SSTL_C_INLINE size_t NAME##_erase(NAME* m, K key); \
  /** @brief Find a key and return its mapped value, or null. */ SSTL_C_INLINE V* NAME##_find(NAME* m, K key); \
  /** @brief Return whether the key is present. */ SSTL_C_INLINE size_t NAME##_count(const NAME* m, K key); \
  /** @brief Return an iterator to the first key not less than `key`. */ SSTL_C_INLINE NAME##_iterator NAME##_lower_bound(const NAME* m, K key); \
  /** @brief Return an iterator to the first key greater than `key`. */ SSTL_C_INLINE NAME##_iterator NAME##_upper_bound(const NAME* m, K key); \
  /** @brief Return the lower-bound side of the equal range. */ SSTL_C_INLINE NAME##_iterator NAME##_equal_range_first(const NAME* m, K key); \
  /** @brief Return the upper-bound side of the equal range. */ SSTL_C_INLINE NAME##_iterator NAME##_equal_range_second(const NAME* m, K key); \
  /** @brief Return an iterator to the smallest key. */ SSTL_C_INLINE NAME##_iterator NAME##_begin(const NAME* m); \
  /** @brief Return the end iterator. */ SSTL_C_INLINE NAME##_iterator NAME##_end(const NAME* m); \
  /** @brief Advance to the next ordered node. */ SSTL_C_INLINE NAME##_iterator NAME##_next(const NAME* m, NAME##_iterator it); \
  /** @brief Move to the previous ordered node, supporting prev(end()). */ SSTL_C_INLINE NAME##_iterator NAME##_prev(const NAME* m, NAME##_iterator it); \
  /** @brief Return a pointer to the pair named by `it`, or null. */ SSTL_C_INLINE NAME##_pair* NAME##_at(NAME* m, NAME##_iterator it); \
  /** @brief Return a pointer to the pair named by `it`, or null. */ SSTL_C_INLINE NAME##_pair* NAME##_deref(NAME* m, NAME##_iterator it);

/** @def SSTL_MAP_DEFINE
 * @brief Define the typed C SSTL API family generated by `SSTL_MAP_DEFINE`.
 * @param NAME Public function/type prefix.
 * @param K Key type stored by value.
 * @param V Mapped value type stored by value.
 * @param CAP Fixed compile-time entry capacity.
 * @param CMP Three-way comparator with signature compatible with `int cmp(const void*, const void*)`.
 */
#define SSTL_MAP_DEFINE(NAME, K, V, CAP, CMP) \
  /** @brief Initialize the map to empty state. */ SSTL_C_INLINE void NAME##_init(NAME* m) { size_t i; m->root = -1; m->free_head = (CAP) == 0 ? -1 : 0; m->size = 0u; for (i = 0u; i != (size_t)(CAP); ++i) { m->nodes[i].parent = -1; m->nodes[i].left = -1; m->nodes[i].right = -1; m->nodes[i].next_free = (i + 1u < (size_t)(CAP)) ? (int)(i + 1u) : -1; m->nodes[i].red = false; m->nodes[i].used = false; } } \
  /** @brief Return the number of stored entries. */ SSTL_C_INLINE size_t NAME##_size(const NAME* m) { return m->size; } \
  /** @brief Return the fixed entry capacity. */ SSTL_C_INLINE size_t NAME##_capacity(const NAME* m) { (void)m; return (size_t)(CAP); } \
  /** @brief Report whether no entries are live. */ SSTL_C_INLINE bool NAME##_empty(const NAME* m) { return m->size == 0u; } \
  /** @brief Report whether capacity is exhausted. */ SSTL_C_INLINE bool NAME##_full(const NAME* m) { return m->size == (size_t)(CAP); } \
  /** @brief Remove every entry and rebuild the free-list. */ SSTL_C_INLINE void NAME##_clear(NAME* m) { NAME##_init(m); } \
  /** @brief Exchange two maps of the same generated type. */ SSTL_C_INLINE void NAME##_swap(NAME* a, NAME* b) { NAME tmp = *a; *a = *b; *b = tmp; } \
  /** @brief Return whether a node index names a red node. */ SSTL_C_INLINE bool NAME##_is_red(const NAME* m, int n) { return n >= 0 && m->nodes[(size_t)n].red; } \
  /** @brief Return the leftmost node in a subtree. */ SSTL_C_INLINE int NAME##_minimum(const NAME* m, int n) { if (n < 0) return -1; while (m->nodes[(size_t)n].left >= 0) n = m->nodes[(size_t)n].left; return n; } \
  /** @brief Return the rightmost node in a subtree. */ SSTL_C_INLINE int NAME##_maximum(const NAME* m, int n) { if (n < 0) return -1; while (m->nodes[(size_t)n].right >= 0) n = m->nodes[(size_t)n].right; return n; } \
  /** @brief Return the ordered successor of a node. */ SSTL_C_INLINE int NAME##_successor(const NAME* m, int n) { int p; if (n < 0) return -1; if (m->nodes[(size_t)n].right >= 0) return NAME##_minimum(m, m->nodes[(size_t)n].right); p = m->nodes[(size_t)n].parent; while (p >= 0 && n == m->nodes[(size_t)p].right) { n = p; p = m->nodes[(size_t)p].parent; } return p; } \
  /** @brief Return the ordered predecessor of a node, or the last node for end. */ SSTL_C_INLINE int NAME##_predecessor(const NAME* m, int n) { int p; if (n < 0) return n == -1 ? NAME##_maximum(m, m->root) : -1; if ((size_t)n >= (size_t)(CAP) || !m->nodes[(size_t)n].used) return -1; if (m->nodes[(size_t)n].left >= 0) return NAME##_maximum(m, m->nodes[(size_t)n].left); p = m->nodes[(size_t)n].parent; while (p >= 0 && n == m->nodes[(size_t)p].left) { n = p; p = m->nodes[(size_t)p].parent; } return p; } \
  /** @brief Rotate a subtree left around node `x`. */ SSTL_C_INLINE void NAME##_rotate_left(NAME* m, int x) { int y = m->nodes[(size_t)x].right; m->nodes[(size_t)x].right = m->nodes[(size_t)y].left; if (m->nodes[(size_t)y].left >= 0) m->nodes[(size_t)m->nodes[(size_t)y].left].parent = x; m->nodes[(size_t)y].parent = m->nodes[(size_t)x].parent; if (m->nodes[(size_t)x].parent < 0) m->root = y; else if (x == m->nodes[(size_t)m->nodes[(size_t)x].parent].left) m->nodes[(size_t)m->nodes[(size_t)x].parent].left = y; else m->nodes[(size_t)m->nodes[(size_t)x].parent].right = y; m->nodes[(size_t)y].left = x; m->nodes[(size_t)x].parent = y; } \
  /** @brief Rotate a subtree right around node `x`. */ SSTL_C_INLINE void NAME##_rotate_right(NAME* m, int x) { int y = m->nodes[(size_t)x].left; m->nodes[(size_t)x].left = m->nodes[(size_t)y].right; if (m->nodes[(size_t)y].right >= 0) m->nodes[(size_t)m->nodes[(size_t)y].right].parent = x; m->nodes[(size_t)y].parent = m->nodes[(size_t)x].parent; if (m->nodes[(size_t)x].parent < 0) m->root = y; else if (x == m->nodes[(size_t)m->nodes[(size_t)x].parent].right) m->nodes[(size_t)m->nodes[(size_t)x].parent].right = y; else m->nodes[(size_t)m->nodes[(size_t)x].parent].left = y; m->nodes[(size_t)y].right = x; m->nodes[(size_t)x].parent = y; } \
  /** @brief Restore red/black insert invariants after adding `z`. */ SSTL_C_INLINE void NAME##_fix_after_insert(NAME* m, int z) { while (z != m->root && NAME##_is_red(m, m->nodes[(size_t)z].parent)) { int p = m->nodes[(size_t)z].parent; int g = m->nodes[(size_t)p].parent; if (p == m->nodes[(size_t)g].left) { int u = m->nodes[(size_t)g].right; if (NAME##_is_red(m, u)) { m->nodes[(size_t)p].red = false; m->nodes[(size_t)u].red = false; m->nodes[(size_t)g].red = true; z = g; } else { if (z == m->nodes[(size_t)p].right) { z = p; NAME##_rotate_left(m, z); p = m->nodes[(size_t)z].parent; g = m->nodes[(size_t)p].parent; } m->nodes[(size_t)p].red = false; m->nodes[(size_t)g].red = true; NAME##_rotate_right(m, g); } } else { int u = m->nodes[(size_t)g].left; if (NAME##_is_red(m, u)) { m->nodes[(size_t)p].red = false; m->nodes[(size_t)u].red = false; m->nodes[(size_t)g].red = true; z = g; } else { if (z == m->nodes[(size_t)p].left) { z = p; NAME##_rotate_right(m, z); p = m->nodes[(size_t)z].parent; g = m->nodes[(size_t)p].parent; } m->nodes[(size_t)p].red = false; m->nodes[(size_t)g].red = true; NAME##_rotate_left(m, g); } } } if (m->root >= 0) m->nodes[(size_t)m->root].red = false; } \
  /** @brief Find a node index by key using the generated comparator hook. */ SSTL_C_INLINE int NAME##_find_node(const NAME* m, K key) { int cur = m->root; while (cur >= 0) { K node_key = m->nodes[(size_t)cur].entry.key; int cmp = (CMP)((const void*)&key, (const void*)&node_key); if (cmp < 0) cur = m->nodes[(size_t)cur].left; else if (cmp > 0) cur = m->nodes[(size_t)cur].right; else return cur; } return -1; } \
  /** @brief Return the first node whose key is not less than `key`. */ SSTL_C_INLINE int NAME##_lower_bound_node(const NAME* m, K key) { int cur = m->root; int best = -1; while (cur >= 0) { K node_key = m->nodes[(size_t)cur].entry.key; int cmp = (CMP)((const void*)&node_key, (const void*)&key); if (cmp < 0) cur = m->nodes[(size_t)cur].right; else { best = cur; cur = m->nodes[(size_t)cur].left; } } return best; } \
  /** @brief Return the first node whose key is greater than `key`. */ SSTL_C_INLINE int NAME##_upper_bound_node(const NAME* m, K key) { int cur = m->root; int best = -1; while (cur >= 0) { K node_key = m->nodes[(size_t)cur].entry.key; int cmp = (CMP)((const void*)&key, (const void*)&node_key); if (cmp < 0) { best = cur; cur = m->nodes[(size_t)cur].left; } else cur = m->nodes[(size_t)cur].right; } return best; } \
  /** @brief Allocate a free tree node and store a pair in it. */ SSTL_C_INLINE int NAME##_allocate_node(NAME* m, K key, V value) { int slot; if (m->free_head < 0) return -1; slot = m->free_head; m->free_head = m->nodes[(size_t)slot].next_free; m->nodes[(size_t)slot].entry.key = key; m->nodes[(size_t)slot].entry.value = value; m->nodes[(size_t)slot].parent = -1; m->nodes[(size_t)slot].left = -1; m->nodes[(size_t)slot].right = -1; m->nodes[(size_t)slot].next_free = -1; m->nodes[(size_t)slot].red = true; m->nodes[(size_t)slot].used = true; return slot; } \
  /** @brief Return a node to the free-list. */ SSTL_C_INLINE void NAME##_release_node(NAME* m, int slot) { m->nodes[(size_t)slot].used = false; m->nodes[(size_t)slot].parent = -1; m->nodes[(size_t)slot].left = -1; m->nodes[(size_t)slot].right = -1; m->nodes[(size_t)slot].red = false; m->nodes[(size_t)slot].next_free = m->free_head; m->free_head = slot; } \
  /** @brief Set a node color when the index names a live tree node. */ SSTL_C_INLINE void NAME##_set_red(NAME* m, int n, bool red) { if (n >= 0) m->nodes[(size_t)n].red = red; } \
  /** @brief Return a node parent index or -1 for a null node. */ SSTL_C_INLINE int NAME##_parent_of(const NAME* m, int n) { return n >= 0 ? m->nodes[(size_t)n].parent : -1; } \
  /** @brief Return a node left-child index or -1 for a null node. */ SSTL_C_INLINE int NAME##_left_of(const NAME* m, int n) { return n >= 0 ? m->nodes[(size_t)n].left : -1; } \
  /** @brief Return a node right-child index or -1 for a null node. */ SSTL_C_INLINE int NAME##_right_of(const NAME* m, int n) { return n >= 0 ? m->nodes[(size_t)n].right : -1; } \
  /** @brief Replace one subtree root with another during erase. */ SSTL_C_INLINE void NAME##_transplant(NAME* m, int old_root, int new_root) { int parent = m->nodes[(size_t)old_root].parent; if (parent < 0) m->root = new_root; else if (old_root == m->nodes[(size_t)parent].left) m->nodes[(size_t)parent].left = new_root; else m->nodes[(size_t)parent].right = new_root; if (new_root >= 0) m->nodes[(size_t)new_root].parent = parent; } \
  /** @brief Restore red/black invariants after removing a black node. */ SSTL_C_INLINE void NAME##_fix_after_erase(NAME* m, int x, int parent) { while (x != m->root && !NAME##_is_red(m, x)) { if (parent < 0) break; if (x == m->nodes[(size_t)parent].left) { int sibling = m->nodes[(size_t)parent].right; if (NAME##_is_red(m, sibling)) { NAME##_set_red(m, sibling, false); NAME##_set_red(m, parent, true); NAME##_rotate_left(m, parent); sibling = m->nodes[(size_t)parent].right; } if (!NAME##_is_red(m, NAME##_left_of(m, sibling)) && !NAME##_is_red(m, NAME##_right_of(m, sibling))) { NAME##_set_red(m, sibling, true); x = parent; parent = NAME##_parent_of(m, x); } else { if (!NAME##_is_red(m, NAME##_right_of(m, sibling))) { NAME##_set_red(m, NAME##_left_of(m, sibling), false); NAME##_set_red(m, sibling, true); NAME##_rotate_right(m, sibling); sibling = m->nodes[(size_t)parent].right; } NAME##_set_red(m, sibling, NAME##_is_red(m, parent)); NAME##_set_red(m, parent, false); NAME##_set_red(m, NAME##_right_of(m, sibling), false); NAME##_rotate_left(m, parent); x = m->root; parent = -1; } } else { int sibling = m->nodes[(size_t)parent].left; if (NAME##_is_red(m, sibling)) { NAME##_set_red(m, sibling, false); NAME##_set_red(m, parent, true); NAME##_rotate_right(m, parent); sibling = m->nodes[(size_t)parent].left; } if (!NAME##_is_red(m, NAME##_right_of(m, sibling)) && !NAME##_is_red(m, NAME##_left_of(m, sibling))) { NAME##_set_red(m, sibling, true); x = parent; parent = NAME##_parent_of(m, x); } else { if (!NAME##_is_red(m, NAME##_left_of(m, sibling))) { NAME##_set_red(m, NAME##_right_of(m, sibling), false); NAME##_set_red(m, sibling, true); NAME##_rotate_left(m, sibling); sibling = m->nodes[(size_t)parent].left; } NAME##_set_red(m, sibling, NAME##_is_red(m, parent)); NAME##_set_red(m, parent, false); NAME##_set_red(m, NAME##_left_of(m, sibling), false); NAME##_rotate_right(m, parent); x = m->root; parent = -1; } } } NAME##_set_red(m, x, false); } \
  /** @brief Erase a tree node in place and preserve red/black structure. */ SSTL_C_INLINE void NAME##_erase_node(NAME* m, int z) { int y = z; int x = -1; int parent = -1; bool y_was_red = m->nodes[(size_t)y].red; if (m->nodes[(size_t)z].left < 0) { x = m->nodes[(size_t)z].right; parent = m->nodes[(size_t)z].parent; NAME##_transplant(m, z, x); } else if (m->nodes[(size_t)z].right < 0) { x = m->nodes[(size_t)z].left; parent = m->nodes[(size_t)z].parent; NAME##_transplant(m, z, x); } else { y = NAME##_successor(m, z); y_was_red = m->nodes[(size_t)y].red; x = m->nodes[(size_t)y].right; if (m->nodes[(size_t)y].parent == z) { parent = y; } else { parent = m->nodes[(size_t)y].parent; NAME##_transplant(m, y, x); m->nodes[(size_t)y].right = m->nodes[(size_t)z].right; m->nodes[(size_t)m->nodes[(size_t)y].right].parent = y; } NAME##_transplant(m, z, y); m->nodes[(size_t)y].left = m->nodes[(size_t)z].left; m->nodes[(size_t)m->nodes[(size_t)y].left].parent = y; m->nodes[(size_t)y].red = m->nodes[(size_t)z].red; } if (!y_was_red) NAME##_fix_after_erase(m, x, parent); NAME##_release_node(m, z); --m->size; if (m->size == 0u) m->root = -1; } \
  /** @brief Insert a key/value pair when the key is absent using the comparator hook. */ SSTL_C_INLINE bool NAME##_insert(NAME* m, K key, V value) { int parent = -1; int cur = m->root; bool went_left = false; int slot; while (cur >= 0) { int cmp; parent = cur; cmp = (CMP)((const void*)&key, (const void*)&m->nodes[(size_t)cur].entry.key); if (cmp < 0) { went_left = true; cur = m->nodes[(size_t)cur].left; } else if (cmp > 0) { went_left = false; cur = m->nodes[(size_t)cur].right; } else return false; } if (m->size == (size_t)(CAP)) { SSTL_C_PANIC("map full"); return false; } slot = NAME##_allocate_node(m, key, value); if (slot < 0) return false; m->nodes[(size_t)slot].parent = parent; if (parent < 0) m->root = slot; else if (went_left) m->nodes[(size_t)parent].left = slot; else m->nodes[(size_t)parent].right = slot; ++m->size; NAME##_fix_after_insert(m, slot); return true; } \
  /** @brief Find a key and return its mapped value, or null. */ SSTL_C_INLINE V* NAME##_find(NAME* m, K key) { int n = NAME##_find_node(m, key); return n >= 0 ? &m->nodes[(size_t)n].entry.value : 0; } \
  /** @brief Return whether the key is present. */ SSTL_C_INLINE size_t NAME##_count(const NAME* m, K key) { return NAME##_find_node(m, key) >= 0 ? 1u : 0u; } \
  /** @brief Return an iterator to the first key not less than `key`. */ SSTL_C_INLINE NAME##_iterator NAME##_lower_bound(const NAME* m, K key) { return NAME##_lower_bound_node(m, key); } \
  /** @brief Return an iterator to the first key greater than `key`. */ SSTL_C_INLINE NAME##_iterator NAME##_upper_bound(const NAME* m, K key) { return NAME##_upper_bound_node(m, key); } \
  /** @brief Return the lower-bound side of the equal range. */ SSTL_C_INLINE NAME##_iterator NAME##_equal_range_first(const NAME* m, K key) { return NAME##_lower_bound(m, key); } \
  /** @brief Return the upper-bound side of the equal range. */ SSTL_C_INLINE NAME##_iterator NAME##_equal_range_second(const NAME* m, K key) { return NAME##_upper_bound(m, key); } \
  /** @brief Erase one key in place, returning whether it was present. */ SSTL_C_INLINE size_t NAME##_erase(NAME* m, K key) { int node = NAME##_find_node(m, key); if (node < 0) return 0u; NAME##_erase_node(m, node); return 1u; } \
  /** @brief Return an iterator to the smallest key. */ SSTL_C_INLINE NAME##_iterator NAME##_begin(const NAME* m) { return NAME##_minimum(m, m->root); } \
  /** @brief Return the end iterator. */ SSTL_C_INLINE NAME##_iterator NAME##_end(const NAME* m) { (void)m; return -1; } \
  /** @brief Advance to the next ordered node. */ SSTL_C_INLINE NAME##_iterator NAME##_next(const NAME* m, NAME##_iterator it) { return NAME##_successor(m, it); } \
  /** @brief Move to the previous ordered node, supporting prev(end()). */ SSTL_C_INLINE NAME##_iterator NAME##_prev(const NAME* m, NAME##_iterator it) { return NAME##_predecessor(m, it); } \
  /** @brief Return a pointer to the pair named by `it`, or null. */ SSTL_C_INLINE NAME##_pair* NAME##_at(NAME* m, NAME##_iterator it) { return (it >= 0 && (size_t)it < (size_t)(CAP) && m->nodes[(size_t)it].used) ? &m->nodes[(size_t)it].entry : 0; } \
  /** @brief Return a pointer to the pair named by `it`, or null. */ SSTL_C_INLINE NAME##_pair* NAME##_deref(NAME* m, NAME##_iterator it) { return NAME##_at(m, it); }

#endif

