/**
 * @file sstl_list.h
 * @brief C99 fixed-capacity doubly linked list backed by a static node pool.
 *
 * Generated list families keep every element in an object-owned node slot and
 * thread unused slots through a free-list. Position APIs are preserved for
 * existing C callers, and iterator helpers expose stable node-slot cursors.
 */
#ifndef SSTL_C_LIST_H
/** @def SSTL_C_LIST_H
 * @brief Include guard for sstl_list.h.
 */
#define SSTL_C_LIST_H
#include "sstl_config.h"

/** @def SSTL_LIST_DECLARE
 * @brief Declare the typed C SSTL API family generated by `SSTL_LIST_DECLARE`.
 */
#define SSTL_LIST_DECLARE(NAME, T, CAP) \
  typedef size_t NAME##_iterator; \
  typedef struct NAME##_node { T value; /**< @brief Stored element value while `used` is true. */ size_t prev; /**< @brief Previous live node slot, or end sentinel. */ size_t next; /**< @brief Next live node slot or free-list link. */ bool used; /**< @brief Whether this pool slot currently owns a live value. */ } NAME##_node; \
  typedef struct NAME { NAME##_node nodes[(CAP) == 0 ? 1 : (CAP)]; /**< @brief Static node pool owned by this list object. */ size_t head; /**< @brief First live node slot, or end sentinel. */ size_t tail; /**< @brief Last live node slot, or end sentinel. */ size_t free_head; /**< @brief First free node slot, or end sentinel. */ size_t size; /**< @brief Number of live nodes. */ } NAME; \
  /** @brief Initialize the list to empty state. */ SSTL_C_INLINE void NAME##_init(NAME* l); \
  /** @brief Remove every element and rebuild the free-list. */ SSTL_C_INLINE void NAME##_clear(NAME* l); \
  /** @brief Return the number of live elements. */ SSTL_C_INLINE size_t NAME##_size(const NAME* l); \
  /** @brief Return the fixed element capacity. */ SSTL_C_INLINE size_t NAME##_capacity(const NAME* l); \
  /** @brief Report whether no elements are live. */ SSTL_C_INLINE bool NAME##_empty(const NAME* l); \
  /** @brief Report whether the fixed capacity is exhausted. */ SSTL_C_INLINE bool NAME##_full(const NAME* l); \
  /** @brief Return an iterator to the first element. */ SSTL_C_INLINE NAME##_iterator NAME##_begin(const NAME* l); \
  /** @brief Return the one-past-end iterator. */ SSTL_C_INLINE NAME##_iterator NAME##_end(const NAME* l); \
  /** @brief Advance an iterator to the next live node. */ SSTL_C_INLINE NAME##_iterator NAME##_next(const NAME* l, NAME##_iterator it); \
  /** @brief Move an iterator to the previous live node, supporting --end. */ SSTL_C_INLINE NAME##_iterator NAME##_prev(const NAME* l, NAME##_iterator it); \
  /** @brief Return a pointer to the element named by `it`. */ SSTL_C_INLINE T* NAME##_at(NAME* l, NAME##_iterator it); \
  /** @brief Return a pointer to the element named by `it`. */ SSTL_C_INLINE T* NAME##_deref(NAME* l, NAME##_iterator it); \
  /** @brief Insert at the back of the list. */ SSTL_C_INLINE bool NAME##_push_back(NAME* l, T x); \
  /** @brief Try to insert at the back without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_push_back(NAME* l, T x); \
  /** @brief Insert at the front of the list. */ SSTL_C_INLINE bool NAME##_push_front(NAME* l, T x); \
  /** @brief Try to insert at the front without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_push_front(NAME* l, T x); \
  /** @brief Insert before the zero-based logical position `pos`. */ SSTL_C_INLINE bool NAME##_insert(NAME* l, size_t pos, T x); \
  /** @brief Try to insert before `pos` without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_insert(NAME* l, size_t pos, T x); \
  /** @brief Erase the zero-based logical position `pos`. */ SSTL_C_INLINE bool NAME##_erase(NAME* l, size_t pos, T* out); \
  /** @brief Remove the first element. */ SSTL_C_INLINE bool NAME##_pop_front(NAME* l, T* out); \
  /** @brief Try to remove the first element without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_pop_front(NAME* l, T* out); \
  /** @brief Remove the last element. */ SSTL_C_INLINE bool NAME##_pop_back(NAME* l, T* out); \
  /** @brief Try to remove the last element without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_pop_back(NAME* l, T* out); \
  /** @brief Compare two values using bytewise equality. */ SSTL_C_INLINE bool NAME##_value_equal(const T* a, const T* b); \
  /** @brief Remove every element equal to `value`. */ SSTL_C_INLINE void NAME##_remove(NAME* l, T value); \
  /** @brief Remove every element for which `pred` returns true. */ SSTL_C_INLINE void NAME##_remove_if(NAME* l, bool (*pred)(const T*)); \
  /** @brief Remove adjacent duplicate elements. */ SSTL_C_INLINE void NAME##_unique(NAME* l); \
  /** @brief Sort elements by swapping node values. */ SSTL_C_INLINE void NAME##_sort(NAME* l, sstl_cmp_fn cmp); \
  /** @brief Move every element from `other` before iterator `pos` using destination-owned slots. */ SSTL_C_INLINE bool NAME##_splice(NAME* l, NAME##_iterator pos, NAME* other); \
  /** @brief Try to move every element from `other` before `pos` without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_splice(NAME* l, NAME##_iterator pos, NAME* other); \
  /** @brief Move one element from `other` before iterator `pos`. */ SSTL_C_INLINE bool NAME##_splice_one(NAME* l, NAME##_iterator pos, NAME* other, NAME##_iterator it); \
  /** @brief Try to move one element from `other` before iterator `pos`. */ SSTL_C_INLINE bool NAME##_try_splice_one(NAME* l, NAME##_iterator pos, NAME* other, NAME##_iterator it); \
  /** @brief Move the half-open range `[first,last)` from `other` before iterator `pos`. */ SSTL_C_INLINE bool NAME##_splice_range(NAME* l, NAME##_iterator pos, NAME* other, NAME##_iterator first, NAME##_iterator last); \
  /** @brief Try to move the half-open range `[first,last)` from `other` before iterator `pos`. */ SSTL_C_INLINE bool NAME##_try_splice_range(NAME* l, NAME##_iterator pos, NAME* other, NAME##_iterator first, NAME##_iterator last); \
  /** @brief Merge sorted `other` into `l` using destination-owned slots. */ SSTL_C_INLINE bool NAME##_merge(NAME* l, NAME* other, sstl_cmp_fn cmp); \
  /** @brief Try to merge sorted `other` into `l` without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_merge(NAME* l, NAME* other, sstl_cmp_fn cmp); \
  /** @brief Return a pointer to the first element. */ SSTL_C_INLINE T* NAME##_front(NAME* l); \
  /** @brief Try to return a pointer to the first element without invoking the active error policy. */ SSTL_C_INLINE T* NAME##_try_front(NAME* l); \
  /** @brief Return a pointer to the last element. */ SSTL_C_INLINE T* NAME##_back(NAME* l); \
  /** @brief Try to return a pointer to the last element without invoking the active error policy. */ SSTL_C_INLINE T* NAME##_try_back(NAME* l); \
  /** @brief Exchange two lists of the same generated type. */ SSTL_C_INLINE void NAME##_swap(NAME* a, NAME* b);

/** @def SSTL_LIST_DEFINE
 * @brief Define the typed C SSTL API family generated by `SSTL_LIST_DEFINE`.
 */
#define SSTL_LIST_DEFINE(NAME, T, CAP) \
  /** @brief Return the private end sentinel used by this generated family. */ SSTL_C_INLINE size_t NAME##_end_sentinel(void) { return (size_t)-1; } \
  /** @brief Initialize the list to empty state. */ SSTL_C_INLINE void NAME##_init(NAME* l) { size_t i; l->head = NAME##_end_sentinel(); l->tail = NAME##_end_sentinel(); l->free_head = (CAP) == 0 ? NAME##_end_sentinel() : 0u; l->size = 0u; for (i = 0u; i != (size_t)(CAP); ++i) { l->nodes[i].prev = NAME##_end_sentinel(); l->nodes[i].next = (i + 1u < (size_t)(CAP)) ? i + 1u : NAME##_end_sentinel(); l->nodes[i].used = false; } } \
  /** @brief Remove every element and rebuild the free-list. */ SSTL_C_INLINE void NAME##_clear(NAME* l) { NAME##_init(l); } \
  /** @brief Return the number of live elements. */ SSTL_C_INLINE size_t NAME##_size(const NAME* l) { return l->size; } \
  /** @brief Return the fixed element capacity. */ SSTL_C_INLINE size_t NAME##_capacity(const NAME* l) { (void)l; return (size_t)(CAP); } \
  /** @brief Report whether no elements are live. */ SSTL_C_INLINE bool NAME##_empty(const NAME* l) { return l->size == 0u; } \
  /** @brief Report whether the fixed capacity is exhausted. */ SSTL_C_INLINE bool NAME##_full(const NAME* l) { return l->size == (size_t)(CAP); } \
  /** @brief Return an iterator to the first element. */ SSTL_C_INLINE NAME##_iterator NAME##_begin(const NAME* l) { return l->head; } \
  /** @brief Return the one-past-end iterator. */ SSTL_C_INLINE NAME##_iterator NAME##_end(const NAME* l) { (void)l; return NAME##_end_sentinel(); } \
  /** @brief Advance an iterator to the next live node. */ SSTL_C_INLINE NAME##_iterator NAME##_next(const NAME* l, NAME##_iterator it) { return (it < (size_t)(CAP) && l->nodes[it].used) ? l->nodes[it].next : NAME##_end_sentinel(); } \
  /** @brief Move an iterator to the previous live node, supporting --end. */ SSTL_C_INLINE NAME##_iterator NAME##_prev(const NAME* l, NAME##_iterator it) { if (it == NAME##_end_sentinel()) return l->tail; return (it < (size_t)(CAP) && l->nodes[it].used) ? l->nodes[it].prev : NAME##_end_sentinel(); } \
  /** @brief Return a pointer to the element named by `it`. */ SSTL_C_INLINE T* NAME##_at(NAME* l, NAME##_iterator it) { return (it < (size_t)(CAP) && l->nodes[it].used) ? &l->nodes[it].value : 0; } \
  /** @brief Return a pointer to the element named by `it`. */ SSTL_C_INLINE T* NAME##_deref(NAME* l, NAME##_iterator it) { return NAME##_at(l, it); } \
  /** @brief Reserve a free node slot and copy `x` into it. */ SSTL_C_INLINE bool NAME##_allocate_node(NAME* l, T x, size_t* out) { size_t slot; if (l->size == (size_t)(CAP) || l->free_head == NAME##_end_sentinel()) { SSTL_C_PANIC("list full"); return false; } slot = l->free_head; l->free_head = l->nodes[slot].next; l->nodes[slot].value = x; l->nodes[slot].prev = NAME##_end_sentinel(); l->nodes[slot].next = NAME##_end_sentinel(); l->nodes[slot].used = true; *out = slot; return true; } \
  /** @brief Return a node slot to the free-list. */ SSTL_C_INLINE void NAME##_release_node(NAME* l, size_t slot) { l->nodes[slot].used = false; l->nodes[slot].prev = NAME##_end_sentinel(); l->nodes[slot].next = l->free_head; l->free_head = slot; } \
  /** @brief Link a node before `pos`, or append when `pos` is end. */ SSTL_C_INLINE void NAME##_link_before(NAME* l, size_t pos, size_t slot) { if (pos == NAME##_end_sentinel()) { l->nodes[slot].prev = l->tail; l->nodes[slot].next = NAME##_end_sentinel(); if (l->tail != NAME##_end_sentinel()) l->nodes[l->tail].next = slot; else l->head = slot; l->tail = slot; } else { size_t prev = l->nodes[pos].prev; l->nodes[slot].prev = prev; l->nodes[slot].next = pos; l->nodes[pos].prev = slot; if (prev != NAME##_end_sentinel()) l->nodes[prev].next = slot; else l->head = slot; } ++l->size; } \
  /** @brief Unlink and release a node, optionally copying its value. */ SSTL_C_INLINE bool NAME##_unlink_node(NAME* l, size_t slot, T* out) { size_t prev; size_t next; if (slot >= (size_t)(CAP) || !l->nodes[slot].used) return false; prev = l->nodes[slot].prev; next = l->nodes[slot].next; if (out) *out = l->nodes[slot].value; if (prev != NAME##_end_sentinel()) l->nodes[prev].next = next; else l->head = next; if (next != NAME##_end_sentinel()) l->nodes[next].prev = prev; else l->tail = prev; NAME##_release_node(l, slot); --l->size; return true; } \
  /** @brief Return the node slot at zero-based logical position `pos`, or end. */ SSTL_C_INLINE size_t NAME##_slot_at(NAME* l, size_t pos) { size_t i = 0u; size_t it = l->head; while (it != NAME##_end_sentinel() && i != pos) { it = l->nodes[it].next; ++i; } return it; } \
  /** @brief Insert at the back of the list. */ SSTL_C_INLINE bool NAME##_push_back(NAME* l, T x) { size_t slot; if (!NAME##_allocate_node(l, x, &slot)) return false; NAME##_link_before(l, NAME##_end_sentinel(), slot); return true; } \
  /** @brief Try to insert at the back without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_push_back(NAME* l, T x) { size_t slot; if (l->size == (size_t)(CAP) || l->free_head == NAME##_end_sentinel()) return false; if (!NAME##_allocate_node(l, x, &slot)) return false; NAME##_link_before(l, NAME##_end_sentinel(), slot); return true; } \
  /** @brief Insert at the front of the list. */ SSTL_C_INLINE bool NAME##_push_front(NAME* l, T x) { size_t slot; if (!NAME##_allocate_node(l, x, &slot)) return false; NAME##_link_before(l, l->head, slot); return true; } \
  /** @brief Try to insert at the front without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_push_front(NAME* l, T x) { size_t slot; if (l->size == (size_t)(CAP) || l->free_head == NAME##_end_sentinel()) return false; if (!NAME##_allocate_node(l, x, &slot)) return false; NAME##_link_before(l, l->head, slot); return true; } \
  /** @brief Insert before the zero-based logical position `pos`. */ SSTL_C_INLINE bool NAME##_insert(NAME* l, size_t pos, T x) { size_t slot; size_t where; if (pos > l->size) { SSTL_C_PANIC("list insert"); return false; } where = pos == l->size ? NAME##_end_sentinel() : NAME##_slot_at(l, pos); if (pos != l->size && where == NAME##_end_sentinel()) return false; if (!NAME##_allocate_node(l, x, &slot)) return false; NAME##_link_before(l, where, slot); return true; } \
  /** @brief Try to insert before `pos` without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_insert(NAME* l, size_t pos, T x) { size_t slot; size_t where; if (pos > l->size || l->size == (size_t)(CAP) || l->free_head == NAME##_end_sentinel()) return false; where = pos == l->size ? NAME##_end_sentinel() : NAME##_slot_at(l, pos); if (pos != l->size && where == NAME##_end_sentinel()) return false; if (!NAME##_allocate_node(l, x, &slot)) return false; NAME##_link_before(l, where, slot); return true; } \
  /** @brief Erase the zero-based logical position `pos`. */ SSTL_C_INLINE bool NAME##_erase(NAME* l, size_t pos, T* out) { size_t slot = NAME##_slot_at(l, pos); if (slot == NAME##_end_sentinel()) { SSTL_C_PANIC("list erase"); return false; } return NAME##_unlink_node(l, slot, out); } \
  /** @brief Remove the first element. */ SSTL_C_INLINE bool NAME##_pop_front(NAME* l, T* out) { if (l->head == NAME##_end_sentinel()) { SSTL_C_PANIC("list empty"); return false; } return NAME##_unlink_node(l, l->head, out); } \
  /** @brief Try to remove the first element without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_pop_front(NAME* l, T* out) { if (l->head == NAME##_end_sentinel()) return false; return NAME##_unlink_node(l, l->head, out); } \
  /** @brief Remove the last element. */ SSTL_C_INLINE bool NAME##_pop_back(NAME* l, T* out) { if (l->tail == NAME##_end_sentinel()) { SSTL_C_PANIC("list empty"); return false; } return NAME##_unlink_node(l, l->tail, out); } \
  /** @brief Try to remove the last element without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_pop_back(NAME* l, T* out) { if (l->tail == NAME##_end_sentinel()) return false; return NAME##_unlink_node(l, l->tail, out); } \
  /** @brief Compare two values using bytewise equality. */ SSTL_C_INLINE bool NAME##_value_equal(const T* a, const T* b) { size_t i; const unsigned char* pa = (const unsigned char*)a; const unsigned char* pb = (const unsigned char*)b; for (i = 0u; i != sizeof(T); ++i) if (pa[i] != pb[i]) return false; return true; } \
  /** @brief Swap two stored values. */ SSTL_C_INLINE void NAME##_swap_values(T* a, T* b) { T tmp = *a; *a = *b; *b = tmp; } \
  /** @brief Remove every element equal to `value`. */ SSTL_C_INLINE void NAME##_remove(NAME* l, T value) { size_t it = l->head; while (it != NAME##_end_sentinel()) { size_t next = l->nodes[it].next; if (NAME##_value_equal(&l->nodes[it].value, &value)) (void)NAME##_unlink_node(l, it, 0); it = next; } } \
  /** @brief Remove every element for which `pred` returns true. */ SSTL_C_INLINE void NAME##_remove_if(NAME* l, bool (*pred)(const T*)) { size_t it = l->head; while (it != NAME##_end_sentinel()) { size_t next = l->nodes[it].next; if (pred(&l->nodes[it].value)) (void)NAME##_unlink_node(l, it, 0); it = next; } } \
  /** @brief Remove adjacent duplicate elements. */ SSTL_C_INLINE void NAME##_unique(NAME* l) { size_t it = l->head; while (it != NAME##_end_sentinel() && l->nodes[it].next != NAME##_end_sentinel()) { size_t next = l->nodes[it].next; if (NAME##_value_equal(&l->nodes[it].value, &l->nodes[next].value)) (void)NAME##_unlink_node(l, next, 0); else it = next; } } \
  /** @brief Sort elements by swapping node values. */ SSTL_C_INLINE void NAME##_sort(NAME* l, sstl_cmp_fn cmp) { size_t i; for (i = l->head; i != NAME##_end_sentinel(); i = l->nodes[i].next) { size_t best = i; size_t j; for (j = l->nodes[i].next; j != NAME##_end_sentinel(); j = l->nodes[j].next) if (cmp((const void*)&l->nodes[j].value, (const void*)&l->nodes[best].value) < 0) best = j; if (best != i) NAME##_swap_values(&l->nodes[i].value, &l->nodes[best].value); } } \
  /** @brief Report whether an iterator is either end or a live node. */ SSTL_C_INLINE bool NAME##_valid_or_end(const NAME* l, NAME##_iterator it) { return it == NAME##_end_sentinel() || (it < (size_t)(CAP) && l->nodes[it].used); } \
  /** @brief Count a valid half-open node range. */ SSTL_C_INLINE size_t NAME##_range_count(const NAME* l, NAME##_iterator first, NAME##_iterator last, bool* ok) { size_t count = 0u; size_t it = first; if (!NAME##_valid_or_end(l, first) || !NAME##_valid_or_end(l, last)) { *ok = false; return 0u; } while (it != last) { if (it == NAME##_end_sentinel() || it >= (size_t)(CAP) || !l->nodes[it].used) { *ok = false; return 0u; } it = l->nodes[it].next; ++count; } *ok = true; return count; } \
  /** @brief Append an already-owned node slot to the output chain. */ SSTL_C_INLINE void NAME##_append_owned_node(NAME* l, size_t slot) { l->nodes[slot].prev = l->tail; l->nodes[slot].next = NAME##_end_sentinel(); if (l->tail != NAME##_end_sentinel()) l->nodes[l->tail].next = slot; else l->head = slot; l->tail = slot; ++l->size; } \
  /** @brief Relink a same-container range before `pos`. */ SSTL_C_INLINE bool NAME##_relink_range_before(NAME* l, NAME##_iterator pos, NAME##_iterator first, NAME##_iterator last) { size_t scan; size_t before; size_t range_tail; size_t after; size_t dest_prev; bool ok; (void)NAME##_range_count(l, first, last, &ok); if (!ok) return false; if (first == last) return true; if (!NAME##_valid_or_end(l, pos)) return false; for (scan = first; scan != last; scan = l->nodes[scan].next) if (scan == pos) return true; before = l->nodes[first].prev; range_tail = (last == NAME##_end_sentinel()) ? l->tail : l->nodes[last].prev; after = last; if (before != NAME##_end_sentinel()) l->nodes[before].next = after; else l->head = after; if (after != NAME##_end_sentinel()) l->nodes[after].prev = before; else l->tail = before; dest_prev = (pos == NAME##_end_sentinel()) ? l->tail : l->nodes[pos].prev; l->nodes[first].prev = dest_prev; l->nodes[range_tail].next = pos; if (dest_prev != NAME##_end_sentinel()) l->nodes[dest_prev].next = first; else l->head = first; if (pos != NAME##_end_sentinel()) l->nodes[pos].prev = range_tail; else l->tail = range_tail; return true; } \
  /** @brief Move every element from `other` before iterator `pos` using destination-owned slots. */ SSTL_C_INLINE bool NAME##_splice(NAME* l, NAME##_iterator pos, NAME* other) { if (l == other) return true; if (pos != NAME##_end_sentinel() && (pos >= (size_t)(CAP) || !l->nodes[pos].used)) { SSTL_C_PANIC("list splice"); return false; } if ((size_t)(CAP) - l->size < other->size) { SSTL_C_PANIC("list splice full"); return false; } return NAME##_try_splice(l, pos, other); } \
  /** @brief Try to move every element from `other` before `pos` without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_splice(NAME* l, NAME##_iterator pos, NAME* other) { return NAME##_try_splice_range(l, pos, other, other->head, NAME##_end_sentinel()); } \
  /** @brief Move one element from `other` before iterator `pos`. */ SSTL_C_INLINE bool NAME##_splice_one(NAME* l, NAME##_iterator pos, NAME* other, NAME##_iterator it) { if (!NAME##_valid_or_end(other, it) || it == NAME##_end_sentinel()) { SSTL_C_PANIC("list splice"); return false; } return NAME##_splice_range(l, pos, other, it, other->nodes[it].next); } \
  /** @brief Try to move one element from `other` before iterator `pos`. */ SSTL_C_INLINE bool NAME##_try_splice_one(NAME* l, NAME##_iterator pos, NAME* other, NAME##_iterator it) { if (!NAME##_valid_or_end(other, it) || it == NAME##_end_sentinel()) return false; return NAME##_try_splice_range(l, pos, other, it, other->nodes[it].next); } \
  /** @brief Move the half-open range `[first,last)` from `other` before iterator `pos`. */ SSTL_C_INLINE bool NAME##_splice_range(NAME* l, NAME##_iterator pos, NAME* other, NAME##_iterator first, NAME##_iterator last) { bool ok; size_t count = NAME##_range_count(other, first, last, &ok); if (!ok || !NAME##_valid_or_end(l, pos)) { SSTL_C_PANIC("list splice"); return false; } if (l != other && (size_t)(CAP) - l->size < count) { SSTL_C_PANIC("list splice full"); return false; } return NAME##_try_splice_range(l, pos, other, first, last); } \
  /** @brief Try to move the half-open range `[first,last)` from `other` before iterator `pos`. */ SSTL_C_INLINE bool NAME##_try_splice_range(NAME* l, NAME##_iterator pos, NAME* other, NAME##_iterator first, NAME##_iterator last) { bool ok; size_t count = NAME##_range_count(other, first, last, &ok); size_t it; if (!ok || !NAME##_valid_or_end(l, pos)) return false; if (count == 0u) return true; if (l == other) return NAME##_relink_range_before(l, pos, first, last); if ((size_t)(CAP) - l->size < count) return false; it = first; while (it != last) { size_t next = other->nodes[it].next; size_t slot; if (!NAME##_allocate_node(l, other->nodes[it].value, &slot)) return false; NAME##_link_before(l, pos, slot); it = next; } it = first; while (it != last) { size_t next = other->nodes[it].next; (void)NAME##_unlink_node(other, it, 0); it = next; } return true; } \
  /** @brief Try to merge sorted `other` into `l` without invoking the active error policy. */ SSTL_C_INLINE bool NAME##_try_merge(NAME* l, NAME* other, sstl_cmp_fn cmp) { size_t left; size_t right; size_t old_head; if (l == other) return true; if ((size_t)(CAP) - l->size < other->size) return false; old_head = l->head; right = other->head; l->head = NAME##_end_sentinel(); l->tail = NAME##_end_sentinel(); l->size = 0u; left = old_head; while (left != NAME##_end_sentinel() || right != NAME##_end_sentinel()) { if (right != NAME##_end_sentinel() && (left == NAME##_end_sentinel() || cmp((const void*)&other->nodes[right].value, (const void*)&l->nodes[left].value) < 0)) { size_t slot; size_t next_right = other->nodes[right].next; (void)NAME##_allocate_node(l, other->nodes[right].value, &slot); NAME##_append_owned_node(l, slot); right = next_right; } else { size_t next_left = l->nodes[left].next; NAME##_append_owned_node(l, left); left = next_left; } } NAME##_init(other); return true; } \
  /** @brief Merge sorted `other` into `l` using destination-owned slots. */ SSTL_C_INLINE bool NAME##_merge(NAME* l, NAME* other, sstl_cmp_fn cmp) { if (!NAME##_try_merge(l, other, cmp)) { SSTL_C_PANIC("list merge full"); return false; } return true; } \
  /** @brief Return a pointer to the first element. */ SSTL_C_INLINE T* NAME##_front(NAME* l) { if (l->head == NAME##_end_sentinel()) { SSTL_C_PANIC("list empty"); return 0; } return &l->nodes[l->head].value; } \
  /** @brief Try to return a pointer to the first element without invoking the active error policy. */ SSTL_C_INLINE T* NAME##_try_front(NAME* l) { return l->head == NAME##_end_sentinel() ? 0 : &l->nodes[l->head].value; } \
  /** @brief Return a pointer to the last element. */ SSTL_C_INLINE T* NAME##_back(NAME* l) { if (l->tail == NAME##_end_sentinel()) { SSTL_C_PANIC("list empty"); return 0; } return &l->nodes[l->tail].value; } \
  /** @brief Try to return a pointer to the last element without invoking the active error policy. */ SSTL_C_INLINE T* NAME##_try_back(NAME* l) { return l->tail == NAME##_end_sentinel() ? 0 : &l->nodes[l->tail].value; } \
  /** @brief Exchange two lists of the same generated type. */ SSTL_C_INLINE void NAME##_swap(NAME* a, NAME* b) { NAME tmp = *a; *a = *b; *b = tmp; }
#endif

