/**
 * @file sstl_optional.h
 * @brief C99 SSTL public header with static, allocation-free API surface.
 *
 * The declarations in this file are part of the local SSTL contract. They are
 * documented for Doxygen consumers and for maintainers reading the headers
 * directly. Keep behavior aligned with the SSTL public contract and tests,
 * and avoid introducing hosted STL dependencies into implementation
 * headers.
 */
#ifndef SSTL_C_OPTIONAL_H
/** @def SSTL_C_OPTIONAL_H
 * @brief Include guard for sstl_optional.h.
 */
#define SSTL_C_OPTIONAL_H
#include "sstl_config.h"

/** @def SSTL_OPTIONAL_DECLARE
 * @brief Declare the typed C SSTL API family generated by `SSTL_OPTIONAL_DECLARE`.
 */
#define SSTL_OPTIONAL_DECLARE(NAME, T) \
  typedef struct NAME { bool has; /**< @brief True when value currently contains meaningful data. */ T value; /**< @brief Inline value storage used when has is true. */ } NAME; \
  /** \
   * @brief Run the generated init operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_init(NAME* o); \
  /** \
   * @brief Run the generated has value operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @return `true` when the documented condition holds; otherwise `false`. \
   */ \
  static SSTL_C_UNUSED bool NAME##_has_value(const NAME* o); \
  /** \
   * @brief Run the generated reset operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_reset(NAME* o); \
  /** \
   * @brief Run the generated set operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @param value Value supplied for comparison, assignment, insertion, or lookup. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set(NAME* o, T value); \
  /** \
   * @brief Run the generated value operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED T* NAME##_value(NAME* o); \
  /** \
   * @brief Run the generated value or operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @param fallback Caller-supplied argument used by this operation. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED T NAME##_value_or(const NAME* o, T fallback); \
  /** \
   * @brief Run the generated try value operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @return Pointer to the requested object on success; null on failure. \
   */ \
  static SSTL_C_UNUSED T* NAME##_try_value(NAME* o);

/** @def SSTL_OPTIONAL_DEFINE
 * @brief Define the typed C SSTL API family generated by `SSTL_OPTIONAL_DEFINE`.
 */
#define SSTL_OPTIONAL_DEFINE(NAME, T) \
  /** \
   * @brief Run the generated init operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_init(NAME* o) { o->has = false; } \
  /** \
   * @brief Run the generated has value operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @return `true` when the documented condition holds; otherwise `false`. \
   */ \
  static SSTL_C_UNUSED bool NAME##_has_value(const NAME* o) { return o->has; } \
  /** \
   * @brief Run the generated reset operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_reset(NAME* o) { o->has = false; } \
  /** \
   * @brief Run the generated set operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @param value Value supplied for comparison, assignment, insertion, or lookup. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED void NAME##_set(NAME* o, T value) { o->value = value; o->has = true; } \
  /** \
   * @brief Run the generated value operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @return Pointer described by the function brief, or null for probe-style failure cases. \
   */ \
  static SSTL_C_UNUSED T* NAME##_value(NAME* o) { if (!o->has) { SSTL_C_PANIC("optional value"); return 0; } return &o->value; } \
  /** \
   * @brief Run the generated value or operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @param fallback Caller-supplied argument used by this operation. \
   * @return Result described by the function brief. \
   */ \
  static SSTL_C_UNUSED T NAME##_value_or(const NAME* o, T fallback) { return o->has ? o->value : fallback; } \
  /** \
   * @brief Run the generated try value operation for this typed SSTL family. \
   * @param o Caller-supplied argument used by this operation. \
   * @return Pointer to the requested object on success; null on failure. \
   */ \
  static SSTL_C_UNUSED T* NAME##_try_value(NAME* o) { return o->has ? &o->value : 0; }

#endif

